# Manifest para mostrar cuando hay dos contenedores en un solo pod (usualmente les llamarian sidecar containers)
# - En este ejemplo, lo que se demostraría es que dos contenedores no pueden escuchar en el mismo puerto, porque comparten la red, pero si pueden escribir porque sus filesystems son independientes por contenedor
# - Recordar que los namespaces compartidos son IPC, Networn y UTS (hostname).
apiVersion: v1
kind: Pod
metadata:
  name: doscont
spec:
  containers:
  - name: cont1
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo cont1 > index.html && python -m http.server 8082']
  - name: cont2
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo cont2 > index.html && python -m http.server 8083']
