# El objetivo de este manifest es ver como hacer un simplisimo Pod y tambien demostrar que en un mismo archivo pueden ir varias definiciones separadas por "---"
apiVersion: v1
kind: Pod
metadata:
  name: podtest2
spec:
  containers:
  - name: cont1
    image: nginx:alpine
    #command: ['sh','-c','echo Hola && sleep 3000']
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
spec:
  containers:
  - name: cont1
    image: nginx:alpine
