# El objetivo de este manifest es ver como hacer un simplisimo Pod y tambien demostrar que en un mismo archivo pueden ir varias definiciones separadas por "---"
# -  Para la seccioon containers.command vale la pena mencionar lo siguiente:
#       * command = ENTRYPOINT en docker
#       * args    = CMD en docker
#    Ejemplos :
#        command: ["/bin/sh"]
#        args: ["-c", "while true; do echo hello; sleep 10;done"]
#
#        command: ["printenv"]
#        args: ["HOSTNAME", "KUBERNETES_PORT"]
#    Referencia: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes

apiVersion: v1
kind: Pod
metadata:
  name: podtest2
spec:
  containers:
  - name: cont1
    image: nginx:alpine
    #command: ['sh','-c','echo Hola && sleep 3000']
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
spec:
  containers:
  - name: cont1
    image: nginx:alpine
